name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dossier_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d dossier_test"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=30

    env:
      # App env
      ENV: ci
      PROM_ENABLED: "false"
      HOSTS: "localhost,127.0.0.1"
      SESSION_SECRET: "ci_session_secret_change_me"

      # DB (local service)
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/dossier_test"

      # Optional: keep these non-empty so /sync/{product} can verify if your tests send signatures
      BRIDGE_SYNC_HMAC_SECRET: "ci_hmac"
      TRUCK_TUNNEL_HMAC_SECRET: "ci_hmac"
      POLEVOLT_HMAC_SECRET: "ci_hmac"
      OCEANGRID_HMAC_SECRET: "ci_hmac"
      VAYUDECK_HMAC_SECRET: "ci_hmac"
      LOCT_HMAC_SECRET: "ci_hmac"
      STARHOP_HMAC_SECRET: "ci_hmac"

      # If you want /atlas/ingest signature enforcement during CI, set this non-empty
      ATLAS_INGEST_SECRET: ""

      # Optional admin fallback (leave hash empty unless you really use it in tests)
      ADMIN_EMAIL: "admin@dossierhr.local"
      ADMIN_PASSWORD_HASH: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # If psycopg ever compiles from source in CI, this prevents pain.
      - name: System deps (Postgres client libs)
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Sanity import (fail fast)
        run: |
          python -c "import dossier_hr_backend; print('import ok')"

      - name: Wait for Postgres
        run: |
          for i in {1..60}; do
            pg_isready -h localhost -p 5432 -U postgres -d dossier_test && exit 0
            sleep 1
          done
          echo "Postgres never became ready" && exit 1

      # Bootstrap tables so your handlers that INSERT/SELECT don't die in CI.
      # This is intentionally "CREATE TABLE IF NOT EXISTS" so it can't hurt prod/staging.
      - name: Bootstrap DB schema (minimal)
        run: |
          python - <<'PY'
          import os
          import psycopg
          from psycopg.rows import dict_row

          dsn = os.environ["DATABASE_URL"]
          with psycopg.connect(dsn, autocommit=True, row_factory=dict_row) as conn:
            conn.execute("""
              CREATE TABLE IF NOT EXISTS roles (
                id UUID PRIMARY KEY,
                name TEXT UNIQUE NOT NULL
              );

              CREATE TABLE IF NOT EXISTS hr_users (
                id UUID PRIMARY KEY,
                email TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                role_id UUID NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT TRUE
              );

              CREATE TABLE IF NOT EXISTS hr_records (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                profile_id TEXT NULL,
                event_type TEXT NOT NULL,
                payload JSONB NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT NOW()
              );

              CREATE TABLE IF NOT EXISTS profiles (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                display_name TEXT NOT NULL,
                external_ref TEXT NULL,
                picture_url TEXT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                deleted_at TIMESTAMP NULL
              );

              CREATE TABLE IF NOT EXISTS reviews (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                reviewer_profile_id TEXT NULL,
                subject_profile_id TEXT NOT NULL,
                stars INT NOT NULL,
                text TEXT NULL,
                sentiment DOUBLE PRECISION NULL,
                weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,
                status TEXT NOT NULL DEFAULT 'approved',
                moderation_meta JSONB NOT NULL DEFAULT '{}'::jsonb,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                moderated_at TIMESTAMP NULL
              );

              CREATE TABLE IF NOT EXISTS review_flags (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                review_id UUID NOT NULL,
                flag_type TEXT NOT NULL,
                severity INT NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT NOW()
              );

              CREATE TABLE IF NOT EXISTS disputes (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                review_id UUID NOT NULL,
                notes TEXT NULL,
                status TEXT NOT NULL DEFAULT 'open',
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                decided_at TIMESTAMP NULL
              );

              CREATE TABLE IF NOT EXISTS verifications (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                profile_id TEXT NOT NULL,
                kind TEXT NOT NULL,
                status TEXT NOT NULL,
                meta JSONB NOT NULL DEFAULT '{}'::jsonb,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                reviewed_at TIMESTAMP NULL
              );

              CREATE TABLE IF NOT EXISTS shadowbans (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                profile_id TEXT NOT NULL,
                reason TEXT NULL,
                active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMP NOT NULL DEFAULT NOW()
              );

              CREATE TABLE IF NOT EXISTS nightly_dumps (
                id UUID PRIMARY KEY,
                status TEXT NOT NULL,
                file_path TEXT NULL,
                run_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL DEFAULT NOW()
              );

              CREATE EXTENSION IF NOT EXISTS pgcrypto;
            """)
          print("DB bootstrap ok")
          PY

      - name: Run tests
        run: |
          pytest -q --maxfail=1
